[capacitor]
n = "S"
x = 0.51
y = 0.29
wall = "N"

[constant]
output = "N"
x = 0.71
y = -0.08

[ground]
g = "N"
x = 0.51
y = -0.08

[pt2]
p1 = "N"
p2 = "W"
x = 0.9
y = 0.11

[pt3]
p1 = "N"
p3 = "S"
x = 0.51
y = 0.11

[resistor]
n = "W"
p = "S"
x = 0.9
y = 0.29

[source]
V = "S"
n = "W"
x = 0.71
y = 0.11
