connect(resistor.p, pt2.p1)
connect(source.p, pt2.p2)
connect(source.n, pt3.p2)
connect(capacitor.n, pt3.p1)
connect(resistor.n, capacitor.p)
connect(ground.g, pt3.p3)
connect(source.V, constant.output)
