[capacitor]
_n = "S"
x = 0.51
y = 0.29
r = "N"

[constant]
_output = "N"
x = 0.71
y = -0.08

[ground]
_g = "N"
x = 0.51
y = -0.08

[pt2]
_p1 = "N"
_p2 = "W"
x = 0.9
y = 0.11

[pt3]
_p1 = "N"
_p3 = "S"
x = 0.51
y = 0.11

[resistor]
_n = "W"
_p = "S"
x = 0.9
y = 0.29

[source]
_V = "S"
_n = "W"
x = 0.71
y = 0.11
