[bv]
x = 0.09
y = 0.15

[dv]
_flange_a = "W"
x = 0.44
y = 0.2

[gv]
_flange = "W"
x = 0.82
y = 0.15

[pt1]
_p1 = "S"
_p3 = "N"
x = 0.65
y = 0.15

[pt2]
_p1 = "S"
_p2 = "W"
_p3 = "N"
x = 0.25
y = 0.15

[sv]
_flange_a = "W"
x = 0.44
y = 0.1
